name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Clear Python cache (optional)
        run: |
          rm -rf ~/.cache/pip

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install Cython buildozer

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true
        env:
          ANDROID_SDK_ROOT: ~/.buildozer/android/platform/android-sdk

      - name: Install Android SDK Build Tools & Accept Licenses
        run: |
          yes | sdkmanager "build-tools;36.0.0" || true
        env:
          ANDROID_SDK_ROOT: ~/.buildozer/android/platform/android-sdk

      - name: Setup Android SDK and Accept Licenses
        run: |
          export SDK_ROOT=$ANDROID_SDK_ROOT
          mkdir -p $SDK_ROOT/cmdline-tools

          # Download and extract commandline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q sdk.zip -d $SDK_ROOT/cmdline-tools
          mv $SDK_ROOT/cmdline-tools/cmdline-tools $SDK_ROOT/cmdline-tools/latest

          # Accept licenses and install build-tools
          $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --licenses <<< "y"
          $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT "build-tools;36.0.0"
        env:
          ANDROID_SDK_ROOT: ~/.buildozer/android/platform/android-sdk


      - name: Build APK
        run: |
          buildozer -v android debug
        env:
          BUILDOZER_ALLOW_ROOT: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: warna-app
          path: bin/*.apk
