name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y zip unzip libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install Cython

      - name: Build APK
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: warna-app.apk
          path: bin/*.apk
          retention-days: 5
          if-no-files-found: error
